#!/bin/bash

# Securely copies files to the Singapore instance
# Version 07/03/2017
# Author Gloire Rubambiza

file_list="../ReceiverSingapore.py ../Bandwidth_Extraction_Singapore ../Save_Estimate.py"
scp  $file_list ec2-user@ec2-54-255-210-106.ap-southeast-1.compute.amazonaws.com:pathload_1.3.2
