#!/bin/bash

# Securely copies the latest files to the Oregon instance in the Dirk group
# Version 07/08/2017
# Author Gloire Rubambiza
file_list="../Dir_Creation ../FileCreation"
scp $file_list ec2-user@ec2-52-37-39-9.us-west-2.compute.amazonaws.com:
