#!/bin/bash

# Extract the lastest bandwith estimate from file
while read f
do
  #echo $f
  set $f
  if [ "$1" == "Available" ]
    then
        summary=$5" "$7
        echo $summary
  fi
done < TempFile.txt
#rm TempFile.txt
